BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[CONGTY] ADD [chinhSachOT] NVARCHAR(150),
[giaiThuong] NVARCHAR(255),
[linhVuc] NVARCHAR(150),
[moHinhCongTy] NVARCHAR(100),
[quocGia] NVARCHAR(100),
[quyMo] NVARCHAR(100),
[tenPhapLy] NVARCHAR(255),
[thoiGianLamViec] NVARCHAR(100);

-- AlterTable
ALTER TABLE [dbo].[CONGVIEC] ADD [luotXem] INT NOT NULL CONSTRAINT [CONGVIEC_luotXem_df] DEFAULT 0;

-- AlterTable
ALTER TABLE [dbo].[MUAQUANGCAO] DROP CONSTRAINT [MUAQUANGCAO_trangThai_df];
ALTER TABLE [dbo].[MUAQUANGCAO] ADD CONSTRAINT [MUAQUANGCAO_trangThai_df] DEFAULT 'Chờ thanh toán' FOR [trangThai];

-- CreateTable
CREATE TABLE [dbo].[BAIVIET] (
    [maBaiViet] VARCHAR(50) NOT NULL,
    [tieuDe] NVARCHAR(255) NOT NULL,
    [anhBiaUrl] VARCHAR(255),
    [noiDung] NVARCHAR(max) NOT NULL,
    [ngayDang] DATETIME2 NOT NULL CONSTRAINT [BAIVIET_ngayDang_df] DEFAULT CURRENT_TIMESTAMP,
    [maCongTy] VARCHAR(50) NOT NULL,
    CONSTRAINT [BAIVIET_pkey] PRIMARY KEY CLUSTERED ([maBaiViet])
);

-- CreateTable
CREATE TABLE [dbo].[THEODOI_CONGTY] (
    [maUngVien] VARCHAR(50) NOT NULL,
    [maCongTy] VARCHAR(50) NOT NULL,
    [ngayTheoDoi] DATETIME2 NOT NULL CONSTRAINT [THEODOI_CONGTY_ngayTheoDoi_df] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [THEODOI_CONGTY_pkey] PRIMARY KEY CLUSTERED ([maUngVien],[maCongTy])
);

-- CreateTable
CREATE TABLE [dbo].[CONGVIEC_KYNANG] (
    [maCongViec] VARCHAR(50) NOT NULL,
    [maKyNang] VARCHAR(50) NOT NULL,
    CONSTRAINT [CONGVIEC_KYNANG_pkey] PRIMARY KEY CLUSTERED ([maCongViec],[maKyNang])
);

-- AddForeignKey
ALTER TABLE [dbo].[BAIVIET] ADD CONSTRAINT [BAIVIET_maCongTy_fkey] FOREIGN KEY ([maCongTy]) REFERENCES [dbo].[CONGTY]([maCongTy]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[THEODOI_CONGTY] ADD CONSTRAINT [THEODOI_CONGTY_maUngVien_fkey] FOREIGN KEY ([maUngVien]) REFERENCES [dbo].[UNGVIEN]([maUngVien]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[THEODOI_CONGTY] ADD CONSTRAINT [THEODOI_CONGTY_maCongTy_fkey] FOREIGN KEY ([maCongTy]) REFERENCES [dbo].[CONGTY]([maCongTy]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[CONGVIEC_KYNANG] ADD CONSTRAINT [CONGVIEC_KYNANG_maCongViec_fkey] FOREIGN KEY ([maCongViec]) REFERENCES [dbo].[CONGVIEC]([maCongViec]) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[CONGVIEC_KYNANG] ADD CONSTRAINT [CONGVIEC_KYNANG_maKyNang_fkey] FOREIGN KEY ([maKyNang]) REFERENCES [dbo].[KYNANG]([maKyNang]) ON DELETE CASCADE ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
