BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[CONGTY] ADD [thanhPho] NVARCHAR(50);

-- AlterTable
ALTER TABLE [dbo].[CONGVIEC] ADD [ngayCapNhat] DATETIME2 NOT NULL CONSTRAINT [CONGVIEC_ngayCapNhat_df] DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE [dbo].[MUAQUANGCAO] DROP CONSTRAINT [MUAQUANGCAO_trangThai_df];
ALTER TABLE [dbo].[MUAQUANGCAO] ADD CONSTRAINT [MUAQUANGCAO_trangThai_df] DEFAULT 'Chờ thanh toán' FOR [trangThai];

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
